# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clase12' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clase12
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Optionally, include the Swift extensions if you're using Swift.
#  pod 'FirebaseFirestoreSwift'
  pod 'Kingfisher', '~> 5.0.0'
  pod 'SVProgressHUD'

end
