# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clase9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clase9
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'SVProgressHUD'

end
